export const SEARCH_SERVICES_REQUEST = "SEARCH_SERVICES_REQUEST"
export const SEARCH_SERVICES_FAILURE = "SEARCH_SERVICES_FAILURE"
export const SEARCH_SERVICES_SUCCESS = "SEARCH_SERVICES_SUCCESS"
export const GO_TO_SERVICE_DETAILS = "GO_TO_SERVICE_DETAILS"
